### ISSUE TITLE
Log out and shutdown buttons in Hera don't do anything

### ISSUE THREAD

**Issue by jonathansantoscunha** [elementary/wingpanel-indicator-session#97] opened 2019-12-16 03:20 UTC
After a certain time Log out and shutdown buttons don't work.

**Comment by cassidyjames** [comment] 2020-01-10 18:26
Gonna mark as a duplicate of #99 since that was filed elsewhere earlier, and has more details.

**Closed by cassidyjames** 2020-01-10 18:26 UTC
