### ISSUE TITLE
Show app icon trays in wingbar

### ISSUE THREAD

**Issue by aitor-gomila** [elementary/wingpanel-indicator-session#180] opened 2023-04-17 18:00 UTC
Currently, the only way to access application trays is by right clicking them in the taskbar. This is not intuitive for people coming from Windows.

It would be more intuitive to add the ability to control app trays from the wingbar, like Ubuntu does. Can't find any screenshots. Maybe it could be a collapsable, removable menu, for people that prefer the MacOS way?

https://www.reddit.com/r/elementaryos/comments/12lzg5v/my_elementary_experience_so_far/

**Comment by danirabbit** [comment] 2023-04-17 18:12
This is a duplicate of https://github.com/elementary/wingpanel/issues/96

**Closed by danirabbit** 2023-04-17 18:12 UTC
